@csrf
@if($classified->exists) @method('PUT') @endif
@php($selectedCategory = old('category_id', $classified->category_id))
@php($selectedSubcategory = old('subcategory_id', $classified->subcategory_id))
<div class="row g-6">
    @if($isAdmin)
    <div class="col-md-6"><label class="form-label" for="user_id">Usuario responsable</label><select id="user_id" name="user_id" class="form-select @error('user_id') is-invalid @enderror" required><option value="">Seleccione...</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('user_id', $classified->user_id) == $user->id)>{{ trim($user->name . ' ' . $user->last_name) }} - {{ $user->email }}</option>@endforeach</select>@error('user_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    @else
    <input type="hidden" name="user_id" value="{{ auth()->id() }}"><div class="col-md-6"><label class="form-label">Usuario responsable</label><input class="form-control" value="{{ auth()->user()->name }}" disabled></div>
    @endif
    <div class="col-md-6"><label class="form-label" for="title">Título</label><input id="title" name="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title', $classified->title) }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="category_id">Categoría</label><select id="category_id" name="category_id" class="form-select @error('category_id') is-invalid @enderror" required data-subcategories-url-template="{{ url('categories') }}/:id/subcategories/json"><option value="">Seleccione...</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($selectedCategory == $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="subcategory_id">Subcategoría</label><select id="subcategory_id" name="subcategory_id" class="form-select @error('subcategory_id') is-invalid @enderror" data-selected="{{ $selectedSubcategory }}"><option value="">Seleccione una categoría primero...</option>@foreach($subcategories as $subcategory)<option value="{{ $subcategory->id }}" @selected($selectedSubcategory == $subcategory->id)>{{ $subcategory->name }}</option>@endforeach</select>@error('subcategory_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="price">Precio</label><input id="price" name="price" type="number" min="0" step="0.01" class="form-control @error('price') is-invalid @enderror" value="{{ old('price', $classified->price) }}" required>@error('price')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="contact">Contacto</label><input id="contact" name="contact" class="form-control @error('contact') is-invalid @enderror" value="{{ old('contact', $classified->contact) }}" required>@error('contact')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="images">Imágenes</label><input id="images" name="images[]" type="file" accept="image/jpeg,image/png,image/webp" multiple class="form-control @error('images') is-invalid @enderror" @required(! $classified->exists)><div class="form-text">{{ $classified->exists ? 'Si cargas nuevas imágenes, reemplazarán las actuales.' : 'Puedes seleccionar varias imágenes.' }}</div>@error('images')<div class="invalid-feedback">{{ $message }}</div>@enderror @error('images.*')<div class="text-danger small">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="description">Descripción</label><textarea id="description" name="description" rows="8" class="form-control @error('description') is-invalid @enderror" required>{{ old('description', $classified->description) }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
@if(! empty($classified->images))<div class="d-flex gap-2 flex-wrap mt-4">@foreach($classified->images as $image)<img src="{{ asset($image) }}" alt="{{ $classified->title }}" class="rounded" width="100" height="100" style="object-fit:cover;">@endforeach</div>@endif
<div class="pt-6 d-flex gap-2"><button class="btn btn-primary mb-5">{{ $classified->exists ? 'Actualizar' : 'Guardar' }}</button><a href="{{ route('classifieds.index') }}" class="btn btn-outline-secondary mb-5">Cancelar</a></div>
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',function(){const category=document.getElementById('category_id');const subcategory=document.getElementById('subcategory_id');function loadSubcategories(){const selected=subcategory.dataset.selected||subcategory.value;subcategory.innerHTML='<option value="">Cargando...</option>';if(!category.value){subcategory.innerHTML='<option value="">Seleccione una categoría primero...</option>';return;}fetch(category.dataset.subcategoriesUrlTemplate.replace(':id',category.value)).then(r=>r.json()).then(items=>{subcategory.innerHTML='<option value="">Seleccione...</option>';items.forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.name;option.selected=String(item.id)===String(selected);subcategory.appendChild(option);});subcategory.dataset.selected='';});}category.addEventListener('change',loadSubcategories);if(category.value)loadSubcategories();});</script>
@endpush
